version: 1.6_2020-02-05  # Has to be in SAM_specs repo
significant figures: 2  # Number of significant figures to keep for the CIGAR mutation counts
separator: '-'  # Separator used in qname
# For exemple Clone1-95056 the separator is '-' -> Clone1 is the chromosome
#             20_62014963_62015458_2:0:0_4:0:0_1a0 the separator is '_' -> 20 is the chromosome
bins: 1000  # Number of bins for the coverage plot